name: Visual Studio CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: MSBuild.exe VS/AsmDude.sln /t:Restore /m
  
    - name: Build
      run: MSBuild.exe VS/AsmDude.sln /t:Rebuild /m
